// === LOCALHOST ===

// Home
### GET home page
GET http://localhost:3000/

// Contacts (all)
### GET all contacts
GET http://localhost:3000/contacts

// Contacts (individual)
### GET individual contact (1)
GET http://localhost:3000/contacts/6a9a09fc8b4684248dfe7339
### GET individual contact (2)
GET http://localhost:3000/contacts/6a9a0ae28b4684248dfe733c
### GET individual contact (3)
GET http://localhost:3000/contacts/6a9a0b158b4684248dfe733d

### CREATE contact (6)
POST http://localhost:3000/contacts/ HTTP/1.1
content-type: application/json

{
  "firstName": "Test-4",
  "lastName": "lastTest-4",
  "email": "test4@gmail.com",
  "favoriteColor": "Black",
  "birthday": "apr-4"
}
### CREATE contact (7) FAILED BECAUSE IT NOT HAS BDAY
POST http://localhost:3000/contacts/ HTTP/1.1
content-type: application/json

{
  "firstName": "Test-5",
  "lastName": "lastTest-5",
  "email": "test5@gmail.com",
  "favoriteColor": "White"
}

// Updating the color from Blue to Dark Blue
### UPDATE individual contact (3)
PUT http://localhost:3000/contacts/6a9a0b158b4684248dfe733d
content-type: application/json

{
  "firstName": "Manuel",
  "lastName": "Lauria",
  "email": "manuellauria@gmail.com",
  "favoriteColor": "Dark Blue",
  "birthday": "may-29"
}
// Go back from Dark Blue to Blue
### UPDATE individual contact (3)
PUT http://localhost:3000/contacts/6a9a0b158b4684248dfe733d
content-type: application/json

{
  "firstName": "Manuel",
  "lastName": "Lauria",
  "email": "manuellauria@gmail.com",
  "favoriteColor": "Blue",
  "birthday": "may-29"
}

// Removing a contact
### DELETE individual contact (id)
DELETE http://localhost:3000/contacts/6aa1f3fb66081b5d30432300



// === PRODUCTION Deploy ===
// https://cse341-unr.onrender.com/

// Home
### GET home page
GET https://cse341-unr.onrender.com/

// Contacts (all)
### GET all contacts
GET https://cse341-unr.onrender.com/contacts

// Contacts (individual)
### GET individual contact (1)
GET https://cse341-unr.onrender.com/contacts/6a9a09fc8b4684248dfe7339
### GET individual contact (2)
GET https://cse341-unr.onrender.com/contacts/6a9a0ae28b4684248dfe733c
### GET individual contact (3)
GET https://cse341-unr.onrender.com/contacts/6a9a0b158b4684248dfe733d


### CREATE contact (6)
POST https://cse341-unr.onrender.com/contacts/ HTTP/1.1
content-type: application/json

{
  "firstName": "Test-4",
  "lastName": "lastTest-4",
  "email": "test4@gmail.com",
  "favoriteColor": "Black",
  "birthday": "apr-4"
}
### CREATE contact (7) FAILED BECAUSE IT NOT HAS BDAY
POST https://cse341-unr.onrender.com/contacts/ HTTP/1.1
content-type: application/json

{
  "firstName": "Test-5",
  "lastName": "lastTest-5",
  "email": "test5@gmail.com",
  "favoriteColor": "White"
}

// Updating the color from Blue to Dark Blue
### UPDATE individual contact (3)
PUT https://cse341-unr.onrender.com/contacts/6a9a0b158b4684248dfe733d
content-type: application/json

{
  "firstName": "Manuel",
  "lastName": "Lauria",
  "email": "manuellauria@gmail.com",
  "favoriteColor": "Dark Blue",
  "birthday": "may-29"
}
// Go back from Dark Blue to Blue
### UPDATE individual contact (3)
PUT https://cse341-unr.onrender.com/contacts/6a9a0b158b4684248dfe733d
content-type: application/json

{
  "firstName": "Manuel",
  "lastName": "Lauria",
  "email": "manuellauria@gmail.com",
  "favoriteColor": "Blue",
  "birthday": "may-29"
}

// Removing a contact
### DELETE individual contact (id)
DELETE https://cse341-unr.onrender.com/contacts/6aa1f69eb23e610c1ef1085c

