// === LOCALHOST ===

// Home
### GET home page
GET http://localhost:3000/

// Carreras (all)
### GET all degrees
GET http://localhost:3000/carreras

// Carreras (individual)
### GET individual degree (1)
GET http://localhost:3000/carreras/6aac8239c8c74d4a0c5dd4ba
### GET individual degree (2)
GET http://localhost:3000/carreras/6aac8465c8c74d4a0c5dd4bd
### GET individual degree (3)
GET http://localhost:3000/carreras/6aac8489c8c74d4a0c5dd4be

### CREATE degree
POST http://localhost:3000/carreras/ HTTP/1.1
content-type: application/json

{
  "carrera": "test Degree",
  "facultadId": "6aac62e3d487cbc054c59707",
  "phone": "(0341) 4804592",
  "durationYears": 5,
  "mail": "test@mail.edu.ar",
  "creditHours": 4000,
  "type": "Carreras de Grado"
}
### CREATE degree --> FAILED BECAUSE IT NOT HAS "type"
POST http://localhost:3000/carreras/ HTTP/1.1
content-type: application/json

{
  "carrera": "test Degree",
  "facultadId": "6aac62e3d487cbc054c59707",
  "phone": "(0341) 4804592",
  "durationYears": 5,
  "mail": "test@mail.edu.ar",
  "creditHours": 4000
}

// Updating the degree type from "Carreras de Grado" to "Doctorados"
### UPDATE individual degree
PUT http://localhost:3000/carreras/6aac8489c8c74d4a0c5dd4be
content-type: application/json

{
  "carrera": "Farmacia",
  "facultadId": "6aac62e3d487cbc054c59707",
  "phone": "(0341) 4804592",
  "durationYears": 5,
  "mail": "estudiantil@fbioyf.edu.ar",
  "creditHours": 3100,
  "type": "Doctorados"
}
// Go back "Carreras de Grado"
### UPDATE individual degree
PUT http://localhost:3000/carreras/6aac8489c8c74d4a0c5dd4be
content-type: application/json

{
  "carrera": "Farmacia",
  "facultadId": "6aac62e3d487cbc054c59707",
  "phone": "(0341) 4804592",
  "durationYears": 5,
  "mail": "estudiantil@fbioyf.edu.ar",
  "creditHours": 3100,
  "type": "Carreras de Grado"
}

// Removing a degree
### DELETE individual degree (id)
DELETE http://localhost:3000/carreras/6aad46a3c431da7a303f8019



// === PRODUCTION Deploy ===
// https://cse341-unr.onrender.com/

// Home
### GET home page
GET https://cse341-unr.onrender.com/

// Carreras (all)
### GET all degrees
GET https://cse341-unr.onrender.com/carreras

// Carreras (individual)
### GET individual degree (1)
GET https://cse341-unr.onrender.com/carreras/6aac8239c8c74d4a0c5dd4ba
### GET individual degree (2)
GET https://cse341-unr.onrender.com/carreras/6aac8465c8c74d4a0c5dd4bd
### GET individual degree (3)
GET https://cse341-unr.onrender.com/carreras/6aac8489c8c74d4a0c5dd4be


### CREATE degree (6)
POST https://cse341-unr.onrender.com/carreras/ HTTP/1.1
content-type: application/json

{
  "carrera": "test Degree",
  "facultadId": "6aac62e3d487cbc054c59707",
  "phone": "(0341) 4804592",
  "durationYears": 5,
  "mail": "test@mail.edu.ar",
  "creditHours": 4000,
  "type": "Carreras de Grado"
}
### CREATE degree --> FAILED BECAUSE IT NOT HAS "type"
POST https://cse341-unr.onrender.com/carreras/ HTTP/1.1
content-type: application/json

{
  "carrera": "test Degree",
  "facultadId": "6aac62e3d487cbc054c59707",
  "phone": "(0341) 4804592",
  "durationYears": 5,
  "mail": "test@mail.edu.ar",
  "creditHours": 4000
}

// Updating the degree type from "Carreras de Grado" to "Doctorados"
### UPDATE individual degree
PUT https://cse341-unr.onrender.com/carreras/6aac8489c8c74d4a0c5dd4be
content-type: application/json

{
  "carrera": "Farmacia",
  "facultadId": "6aac62e3d487cbc054c59707",
  "phone": "(0341) 4804592",
  "durationYears": 5,
  "mail": "estudiantil@fbioyf.edu.ar",
  "creditHours": 3100,
  "type": "Doctorados"
}
// Go back "Carreras de Grado"
### UPDATE individual degree
PUT https://cse341-unr.onrender.com/carreras/6aac8489c8c74d4a0c5dd4be
content-type: application/json

{
  "carrera": "Farmacia",
  "facultadId": "6aac62e3d487cbc054c59707",
  "phone": "(0341) 4804592",
  "durationYears": 5,
  "mail": "estudiantil@fbioyf.edu.ar",
  "creditHours": 3100,
  "type": "Carreras de Grado"
}

// Removing a degree
### DELETE individual degree (id)
DELETE https://cse341-unr.onrender.com/carreras/

